### ISSUE TITLE
missing Dockerfile?

### ISSUE THREAD

**Issue by theguly** [mwalczak/sf-easy#3]
given docker-compose.yml request a build for php-fpm, nginx, and frontend at least, i expected to have Dockerfile in ./docker/service directory for containers that don't come with an official image

**Comment by mwalczak** [comment]
absolutely right, I was developing it using symfony-cli but it's better for everyone to switch to docker, checkout last commit, it should be fixed now

**Comment by theguly** [comment]
amazing, thanks for the quick response!
